### ISSUE TITLE
How to use it with horizontal split?

### ISSUE THREAD

**Issue by gasacchi** [beauwilliams/focus.nvim#14]
Hi, Thanks for the plugin, i really like it.
i have question, how can i use in horizontal split like in preview?
my monitor use 1366x768, try to change height nothing changes.

**Comment by beauwilliams** [comment]
Hi there, thanks for the feedback glad you are liking focus.

Unfortunately due to issues with minimal screen real estate and how vim handles it, the only option might be to reduce focus size, but you might not be able to reduce it enough to make a difference as there is a minimum size a split should be. This issue was discussed previously here --> https://github.com/beauwilliams/focus.nvim/commit/e39cfc97be2f42fb33bc9946f4d1f81ed8c39cc1

I will close this for now. Please feel free to reopen, if you feel that I've made the wrong assumption here etc :)
