### ISSUE TITLE
Feature Request: Allow specifying signcolumn behavior

### ISSUE THREAD

**Issue by kmclarnon** [beauwilliams/focus.nvim#40]
Unless I've missed something it doesn't seem like there is a way to enable any signcolumn behavior other than `auto`, which (for me) causes annoying movements of code I'm editing with lsp diagnostics.  It would be nice if we could provide the value to set signcolumn to on WinEnter as part of the setup.  Eg. something like 

```
require('focus').setup({
  enable = true, 
  signcolumn = true,
  signcolumn_value = "yes"
})
```

For now I've modified my fork to use the value I want directly, so this isn't a high priority issue for me

Thanks for this great plugin!

**Comment by beauwilliams** [comment]
Glad you are enjoying focus 😄 

If I am understanding correctly, you can set signcolumn to false in the focus setup, and then put something along the lines of `set signcolumn=yes` in your configs. I just tried it then. I can add something into the readme FAQ or otherwise do you think it should definitely be an option included in focus?

The intention was that is you set auto signcolumn to false then you can configure it yourself using any option you like in your configs.

**Comment by kmclarnon** [comment]
Ah I think I haven't done a good job describing the behavior I was hoping for.  I would like to leverage the auto commands that are set up by focus so that I can have `signcolumn=yes` on the active split only.  When I'm actively editing a specific split then having the `signcolumn=auto` is unfortunate, but once I move away from that split to another one, I would like focus to do what it currently does when 'setup({signcolumn=true})` and set `signcolumn=no` to avoid wasting space

Does that make sense?

**Comment by beauwilliams** [comment]
> Ah I think I haven't done a good job describing the behavior I was hoping for. I would like to leverage the auto commands that are set up by focus so that I can have `signcolumn=yes` on the active split only. When I'm actively editing a specific split then having the `signcolumn=auto` is unfortunate, but once I move away from that split to another one, I would like focus to do what it currently does when `setup({signcolumn=true})` and set `signcolumn=no` to avoid wasting space
> 
> Does that make sense?

Yes this makes sense. Let me get onto it

**Comment by gegoune** [comment]
Setting it to `auto` is not fully resolving the issue. There is way more possible options for `signcolumn`. Please see `:h `signcolumn'`:

```
When and how to draw the signcolumn. Valid values are:
   "auto"       only when there is a sign to display
   "auto:[1-9]" resize to accommodate multiple signs up to the
                given number (maximum 9), e.g. "auto:4"
   "auto:[1-8]-[2-9]"
                resize to accommodate multiple signs up to the
                given maximum number (maximum 9) while keeping
                at least the given minimum (maximum 8) fixed
                space. The minimum number should always be less
                than the maximum number, e.g. "auto:2-5"
   "no"         never
   "yes"        always
   "yes:[1-9]"  always, with fixed space for signs up to the given
                number (maximum 9), e.g. "yes:3"
   "number"     display signs in the 'number' column. If the number
                column is not present, then behaves like 'auto'.
```

Probably the best way is to save its initial value in some state var, so read `signcolumn` if `setup { signcolumn = true }`.

**Comment by beauwilliams** [comment]
Okay, I

**Comment by gegoune** [comment]
Are you saying that if user has `focus.signcolumn` enabled (I don't) then the required way will be to set it through focus.nvim's configuration? That doesn't feel right. I think focus.nvim could manage it's internal state where initial (user set) values would be stored.

Not sure how to solve the issue of having option changed in running nvim rather than at startup (as focus.nvim would have startup value, not update one).

**Comment by beauwilliams** [comment]
Yes so because what we are doing is creating an autocommand, the only way is to specify the user setting when creating the autocommand. 

We could perhaps instead recreate the autocommands say on BufEnter events and grab the variable from vim itself and not configure it in focus.

Is this what you are referring to? We can do it, but it would require the autocommands to be set up at BufEnter I am pretty sure.

**Comment by gegoune** [comment]
It could be 

```lua
{ 'BufEnter,WinEnter', '*', 'setlocal signcolumn=' .. vim.opt.signcolumn:get() },
```

maybe? With some note in readme that `signcolumn` needs to be set before running `setup()`.

It would still disregard user's change of that option after changing windows once.

**Comment by beauwilliams** [comment]
> ```lua
> vim.opt.signcolumn:get()
> ```

Thanks! This is much better

**Comment by beauwilliams** [comment]
@kmclarnon @gegoune should not grab the var. you can run :set signcolumn=yes

let me know if any issues with it.

**Comment by kmclarnon** [comment]
awesome, thanks!

**Comment by beauwilliams** [comment]
Do we think this is safe to close now?

**Comment by kmclarnon** [comment]
Yep, sorry for the delay 👍

**Comment by beauwilliams** [comment]
All good no worries 👍  Thank you
