### ISSUE TITLE
nvimtree window is very large

### ISSUE THREAD

**Issue by xuliefeng** [beauwilliams/focus.nvim#79]
Hi, the nvimtree window is huge. How to deal with this, adding ignore is not enough

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/11550443/156969606-8680a854-d1b4-4760-aa4d-dfbe0fb7d067.png">

**Comment by tomaskallup** [comment]
I have the same problem with following config:
```lua
require'focus'.setup({excluded_filetypes = {"NvimTree", "toggleterm"}})
```

**Comment by tomaskallup** [comment]
Adding to this, I think this is because of the way focus integrates with NvimTree, it detects it by buffer name, which changed recently see https://github.com/kyazdani42/nvim-tree.lua/commit/0e7856fd8de18edaaee8fa0c2f2c9432c973aef5. 

I think [this](https://github.com/beauwilliams/focus.nvim/blob/e51b125fb8e70b504afdf343cc77f44938f306e9/lua/focus/modules/autocmd.lua#L41) should be changed to `NvimTree_*`

**Comment by beauwilliams** [comment]
Aha, okay let me review the PR. Always fun when upstream changes. Thanks for the PR!!
